[package]
name = "time-warp-ide"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = "0.24"
egui = "0.24"
rfd = "0.14"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"
anyhow = "1.0"