name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Build Sphinx docs
        working-directory: docs
        run: |
          make html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
